#!/bin/sh

target=${1-~/public_html/source/mdadm}
if [ -d $target ]
then :
else echo $target is not a directory
     exit 2
fi
set `grep '^char Version' ReadMe.c `
version=`echo $7 | sed 's/v//'`
grep "^Version: *$version$" mdadm.spec > /dev/null 2>&1 || 
 {
   echo mdadm.spec does not mention version $version.
   exit 1
 }
echo version = $version
base=mdadm-$version.tgz
if [ -f $target/$base ] 
then 
  echo $target/$base exists.
  exit 1
fi
trap "rm $target/$base; exit" 1 2 3
( cd .. ; ln -s mdadm mdadm-$version ; tar chvf - --exclude="TAGS" --exclude='*,v' --exclude='*.o' --exclude mdadm --exclude=mdadm'.[^ch0-9]' --exclude=RCS mdadm-$version ; rm mdadm-$version ) | gzip --best > $target/$base
chmod a+r $target/$base
ls -l $target/$base

rpm -ta $target/$base
find /home/neilb/src/RPM -name "*mdadm-$version-*" \
 -exec cp {} $target/RPM \;
