#!/bin/sh

target=${1-~/public_html/source/mdctl}
if [ -d $target ]
then :
else echo $target is not a directory
     exit 2
fi
set `grep '^char Version' ReadMe.c `
version=`echo $7 | sed 's/v//'`
echo version = $version
base=mdctl-$version.tgz
if [ -f $target/$base ] 
then 
  echo $target/$base exists.
  exit 1
fi
trap "rm $target/$base; exit" 1 2 3
( cd .. ; ln -s mdctl mdctl-$version ; tar czhvf - --exclude='*,v' --exclude='*.o' --exclude mdctl --exclude=RCS mdctl-$version ; rm mdctl-$version )  > $target/$base
chmod a+r $target/$base
ls -l $target/$base
